# Generated by Django 5.1.15 on 2026-06-15 16:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('name_fa', models.CharField(blank=True, help_text='Optional Persian label shown in the sidebar.', max_length=80, verbose_name='Persian name')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian (Farsi)')], default='en', help_text='Drives font + text direction (RTL for Persian) on the site.', max_length=2)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in the post list.')),
                ('body', models.TextField(help_text='Markdown. Use ``` fences for code blocks.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('source_url', models.URLField(blank=True, help_text='Optional link shown under the title (e.g. GitHub repo).')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('audio', 'Music / audio'), ('file', 'File / download'), ('book', 'Book'), ('image', 'Image')], default='file', max_length=8)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='attachments/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.post')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
